### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Selbi182** [Selbi182/SetlistFmToSpotifyPlaylist#1]
Here's a list of all the fixes and improvements I have planned. Feel free to comment if you have any other ideas!

- [ ] Allow to manually insert missed songs by providing Spotify track links
- [x] Add more detailed progress descriptions during conversion
- [x] Fix Fall Out Boy's _Grand Theft Autumn/Where Is Your Boy_ not being found (possibly related to the slash character)
- [x] Remember settings on page refresh
- [ ] (Idea) Add fake unavailable songs to the playlist to mark set names and/or missed songs
- [x] Eventually get rid off the Strict Search button when everything finally just works
- [x] Fix the ¥$ collab
- [x] Favor tracks from the exact album name from setlist.fm's API
